# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# TODO add roxygenyze https://lorenzwalthert.github.io/precommit/articles/available-hooks.html
# TODO add one that bumps dev version (manually write)
# TODO check what each of these does
# TODO add pre-commit to README
# TODO check extrachecks
# TODO check the email