# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# R specific hooks: https://github.com/lorenzwalthert/precommit
fail_fast: true
repos:
-   repo: local
    hooks:
    - id: roxygenize
      name: roxygenize
      description: Roxygenize R code
      entry: Rscript -e 'devtools::document()'
      language: system
    - id: up-dev-version
      name: up-dev-version
      description: Bumps the dev version in DESCRIPTION
      entry: pixi run up-dev # inside pixi because that's where pre-commit is
      language: system

# TODO check extrachecks
# TODO check the email