# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    - id: up-dev-version
      name: up-dev-version
      description: Bumps the dev version in DESCRIPTION
      entry: pixi run up-dev
# TODO add roxygenyze https://lorenzwalthert.github.io/precommit/articles/available-hooks.html
# TODO add one that bumps dev version (manually write)
# TODO check what each of these does
# TODO add pre-commit to README
# TODO check extrachecks
# TODO check the email