[project]
name = "settingsSync"
authors = ["notPlancha <Andre_Plancha@iscte-iul.pt>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
hook-install = "pre-commit install --hook-type pre-push"
radian = "radian"
up-dev = "python hook_scripts/up-dev-version.py"

[dependencies]
pre-commit = ">=3.6.0,<3.7"
radian = ">=0.6.11,<0.7"
expression = ">=5.0.2,<5.1"
icecream = ">=2.1.3,<2.2"
click = ">=8.1.7,<8.2"
pyprojroot = ">=0.3.0,<0.4"
